repos:
  - repo: builtin
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-yaml
      - id: check-toml
      - id: check-json
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo +nightly fmt --all
        language: system
        types: [rust]
        pass_filenames: false
      - id: cargo-sort
        name: cargo sort
        entry: cargo sort --workspace
        language: system
        files: ^Cargo\.toml$
        pass_filenames: false
      - id: cargo-build
        name: cargo build
        entry: cargo build --workspace --locked
        language: system
        pass_filenames: false
