- name: worker node setup
  hosts: worker_nodes
  become: false
  tasks:
    - name: ping worker nodes
      ansible.builtin.ping:
      tags: [always]
  roles:
    - role: cloudflared
      tags: [cloudflared]
    - role: firecracker
      tags: [firecracker]
    - role: crack402_node
      tags: [crack402_node]
