- name: worker node setup
  hosts: worker_nodes
  become: false
  roles:
    - role: cloudflared
      tags: [cloudflared]
    - role: firecracker
      tags: [firecracker]
    - role: crack402_node
      tags: [crack402_node]
